version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    volumes:
      # Mount source code for development (optional)
      - .:/home/src
    command: node tbi-server/dist/index.js

  # Development service (optional)
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000" # Client dev server
      - "8080:8080" # Server dev server
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/src
      - /home/src/node_modules
      - /home/src/tbi-client/node_modules
      - /home/src/tbi-server/node_modules
    command: /bin/sh -c "cd tbi-server && pnpm run start"
