version: "3.8"

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped

  # Development service for local development
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/src
      - /home/src/node_modules
    command: /bin/sh -c "cd tbi-server && pnpm run dev"
    profiles:
      - dev
